### ISSUE TITLE
[Adapter Module]: Implement Metastable Token Adapter 

### ISSUE THREAD

**Issue by njokuScript** [Descent-Collective/protocol-v1#49]
### Description
Create a token adapter contract that facilitates the burning and minting of metastable tokens. The adapter should interact directly with the Vault Contracts to manage metastable balances.

### Tasks

- [ ] Design the metastable token adapter contract interface
- [ ] Implement functions for minting and burning of metastable tokens as well as representing the balance on the vault contracts
- [ ] Integrate the adapter with the Vault Contracts
- [ ] Write tests to ensure the functionality of the metastable token adapter

NB: This was previously implemented here: https://github.com/Descent-Collective/protocol-core/blob/module/adapter/contracts/adapter.sol#L89
